<%@ Page Title="" Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" 
    CodeFile="AdminFeedback.aspx.cs" Inherits="Feedback" %>
<%@ OutputCache VaryByParam="none" Duration="1" NoStore="true" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <h1 style="text-align:center; color:blue; font-size:xx-large; font-family:'Meiryo UI'">All FeedBacks</h1>
    <div style="background-color: #000000; color: #FFFFFF; height: 150px; 
width:100%;" align="center">
        
    <asp:GridView ID="GridView1" runat="server" AllowSorting="True" 
        AutoGenerateColumns="False" DataKeyNames="Id" AutoGenerateDeleteButton="true" 
        DataSourceID="SqlDataSource1"   >
        <Columns>
            <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" InsertVisible="false"
                 ReadOnly="true"  />

            <asp:BoundField DataField="name" HeaderText="name" SortExpression="name" />

            <asp:BoundField DataField="address" HeaderText="address" SortExpression="address" />

            <asp:BoundField DataField="city" HeaderText="city" SortExpression="city" />

            <asp:BoundField DataField="m_no" HeaderText="m_no" SortExpression="m_no" />

            <asp:BoundField DataField="email_id" HeaderText="email_id" SortExpression="email_id" />

            <asp:BoundField DataField="comment" HeaderText="comment" SortExpression="comment" />

          

        </Columns>
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server"
         ConnectionString="<%$ ConnectionStrings:mydb %>" 
   
        SelectCommand="SELECT * FROM [feedback]" 
         DeleteCommand="DELETE FROM [feedback] WHERE [Id] = @Id;">
        <DeleteParameters>
            <asp:ControlParameter ControlID="GridView1" Name="id"  />
        </DeleteParameters>
       
         </asp:SqlDataSource>

        </div>
    
 <!--InsertCommand="INSERT INTO [feedback] ([name], [address], [city], [m_no], [email_id], [comment]) VALUES (@name, @address, @city, @m_no, @email_id, @comment)" -->
    </asp:Content>
